server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**
